### ISSUE TITLE
Using `cid.contact` as HTTP announce sender URL results in 404

### ISSUE THREAD

**Issue by masih** [ipni/go-libipni#36]
The sender implementation concatenates `/announce` to a given URL _[if no path is present](https://github.com/ipni/go-libipni/blob/main/announce/httpsender/sender.go#L55-L57)_. But the actual path for sending announcements is `/ingest/announce`. 
This means a user would have to specify the full announce URL `https://cid.contact/ingest/announce`, which makes the default path unusable.

Change the default announce path to include `/ingest` prefix.

**Comment by gammazero** [comment]
The problem is that the endpoint was changed to `/announce` here:
https://github.com/ipni/storetheindex/blob/main/server/ingest/http/server.go#L56 (see [deprecation](https://github.com/ipni/storetheindex/blob/main/server/ingest/http/server.go#L60-L61))
but not here:
https://github.com/ipni/storetheindex/blob/main/assigner/server/server.go#L48

**Comment by masih** [comment]
if `ingest/announce` is deprecated @gammazero can I ask you to update the open API spec in ipni/specs please

**Comment by gammazero** [comment]
@masih Updated spec: https://github.com/ipni/specs/pull/17/files
